var list = [
// "被每一个人弹额",
// "亲一个异性的额头。",
"Push Up 20 times. Pick another punishment if give up",
// "拉铁5 set, 然后说我要做猛男",
// "做 Pumping 10 下，屁股坐着异性",
// "被其中一个异性拉ketiak 毛",
// "跑步机快跑 3 分钟，说xxx 我一定要追到你",
// "给任意一个异性挖鼻屎",
"Laugh like a crazy person for 10 seconds",
// "在健身房问一个陌生人，我的屁股/肌肉大吗？",
"弹皮筋。输的一方任由赢方怎么弹",
"Let other player stickle your foot for 10 seconds",
"Let other players pinch part of your body",
"Get hit 10 times by using slippers",
"Use buttock to spell out your name",
// "男的用胳膊从正面量女的胸围or女的量男的腰围",
// "侧抱互相喂酒、喂吃的",
// "和左数第一个异性亲一下",
// "脱一件衣服持续到结束",
// "男:脱衣说我是猛男，女:摸自己的胸说是时候隆胸了",
// "背起右边第一个女生",
// "背起右边第一个男生",
// "和一个异性对换衣服",
// "十指交扣握住保持一轮",
// "男： 被每一个人捏奶头 女：从新选过",
// "左手拉右耳，右手拉左耳，从桌子底下过",
// "亲左数第二个异性的额头",
// "和左边第一个异性换穿上衣",
// "对窗外大喊“我好寂寞啊",
// "女生坐男生小腿上，男生做仰卧起坐",
// "在每个人面前挖鼻孔",
// "讲你第一次做爱的经历",
// "问你左边玩家的香港脚",
"Get Slapped by other players",
"Do a chicken dance for  5 minutes",
"Sniff the armpits of other players",
"Let other player/s draw your face",
// "Do push ups until you can’t do any more,\n wait 5 seconds, and then do one more",
// "Switch clothes with someone of the\n opposite sex in the group for three rounds",
// "Take off one piece of your clothing",
"Get slapped on the face by using slippers",
// "Choose someone from the group to give you a spanking",
// "Lick the face of the opposite sex player closest to you",
// "男的用胳膊从正面量女的胸围or女的量男的腰围",
// "背起右边第一 个女生",
// "邀请一位异性为你唱情歌，或邀请一位异性与你情歌对唱",
// "对亲脖子",
// "Let the person on your left hold\n your penis for 1 minute (For boy only)",
// "Who here would you most like to make out with?",
// "Transfer an icecube from your mouth\n to the person’s mouth on your right.",
// "Let someone shave part of your body",
// "Take off your underwear and put it on your head from now",
 "Sing out loud"
];


function insert () {
  var s=document.getElementById("truth_dare_content_add").value +"";
  var ss=s.toString();
  list.push(ss);
  document.getElementById("truth_dare_content_add").value="";
}
